# 🐼 Pandas - Class 1: Introduction & Setup
Welcome to your first class on **Pandas**. In this session, we'll learn what Pandas is, why we use it, and how to get started with Series and DataFrames.

## 1 What is Pandas and Why Use It?
Pandas is a powerful **Python library** for data analysis and manipulation.

Key points:
- Provides two main data structures: **Series** (1D) and **DataFrame** (2D).
- Makes working with tabular data easy and fast.
- Ideal for cleaning, transforming, and analyzing datasets.
- Works well with other libraries like NumPy, Matplotlib, and Scikit-Learn.

## 2 Installing & Importing Pandas
To install pandas, open your terminal or command prompt and run:
```bash
pip install pandas
```
Then, you can import it in Python as follows:

In [2]:
import pandas as pd

## 3 Understanding Series & DataFrame
- **Series**: One-dimensional labeled array, like a column in Excel.
- **DataFrame**: Two-dimensional table, similar to an Excel sheet or SQL table.

### Creating a Series from Python Lists or Dictionaries

In [3]:
a = [10, 20, 30, 40, 50]
b = pd.Series(a, name = "Marks") # This is series only a single column
print(b)

0    10
1    20
2    30
3    40
4    50
Name: Marks, dtype: int64


In [4]:
c = {'Chetan' : 81, 'Mohit' : 90, 'Tanishkq' : 88, 'Rohan' : 91}
print(pd.Series(c, name = "Marks"))

pd.Series(c, name = "marks")

Chetan      81
Mohit       90
Tanishkq    88
Rohan       91
Name: Marks, dtype: int64


,marks
Chetan,81
Mohit,90
Tanishkq,88
Rohan,91


### Creating a DataFrame

In [5]:
d = {
    'Name' : ['Chetan', 'Devraj', 'Tanishkq', 'Hariom'],
    'Marks' : [81, 77, 90, 56],
    'Subject' : ['Maths', 'Science', 'Politics', 'Hindi'],
}
df = pd.DataFrame(d)
print(df)

       Name  Marks   Subject
0    Chetan     81     Maths
1    Devraj     77   Science
2  Tanishkq     90  Politics
3    Hariom     56     Hindi


### Creating DataFrame from NumPy Arrays

In [6]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(arr, "\n")

df = pd.DataFrame(arr, columns = ['A', 'B', 'C'])
print(df)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


### Reading CSV / Excel Files (Sneak Peek)
You can read external data using:
```python
pd.read_csv('file.csv')  # Utility Tools / commands
```
```python
pd.read_excel('file.xlsx')
```
We will explore this in detail later.

---
**Summary**
- Pandas is a must-know library for data analysis.
- We learned about Series & DataFrames.
- We saw how to create them from lists, dictionaries, NumPy arrays, and got a sneak peek at CSV/Excel files.